//Source code generated by AppGPT (www.appgpt.tech)
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  base: '/a99f25e8e/',
  build: {
    outDir: '.output/a99f25e8e',
    emptyOutDir: true,
  },
  server: {
    host: true,
    strictPort: true,
    port: 5173,
  },
});
