//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Films: {
      name: 'Films',
      fields: {
        title: 'Title',
        releaseDate: 'Release Date',
        director: 'Director',
        actors: 'Actors',
        genre: 'Genre',
        description: 'Description',
        id: 'id',
      },
    },
    Directors: {
      name: 'Directors',
      fields: { name: 'Name', dateOfBirth: 'Date Of Birth', id: 'id' },
    },
    Actors: {
      name: 'Actors',
      fields: { name: 'Name', dateOfBirth: 'Date Of Birth', id: 'id' },
    },
  },
};
const frResources = {
  resources: {
    Films: {
      name: 'Films (fr)',
      fields: {
        title: 'Title (fr)',
        releaseDate: 'Release Date (fr)',
        director: 'Director (fr)',
        actors: 'Actors (fr)',
        genre: 'Genre (fr)',
        description: 'Description (fr)',
        id: 'id',
      },
    },
    Directors: {
      name: 'Directors (fr)',
      fields: {
        name: 'Name (fr)',
        dateOfBirth: 'Date Of Birth (fr)',
        id: 'id',
      },
    },
    Actors: {
      name: 'Actors (fr)',
      fields: {
        name: 'Name (fr)',
        dateOfBirth: 'Date Of Birth (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
